//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facevalue
    {
        public long id { get; set; }
        public long appid { get; set; }
        public string gamename { get; set; }
        public string price { get; set; }
        public decimal value { get; set; }
    }
}
