//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public long id { get; set; }
        public string appid { get; set; }
        public Nullable<decimal> money { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    }
}
