//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManage.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrderEntities : DbContext
    {
        public OrderEntities()
            : base("name=OrderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<facevalue> facevalues { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<platform> platforms { get; set; }
        public virtual DbSet<processOrder> processOrders { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<commission> commissions { get; set; }
        public virtual DbSet<game> games { get; set; }
    }
}
