//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public long id { get; set; }
        public string 订单号 { get; set; }
        public string 订单详情 { get; set; }
        public string 状态 { get; set; }
        public Nullable<decimal> 提成 { get; set; }
        public long 创建人 { get; set; }
        public Nullable<System.DateTime> 创建时间 { get; set; }
        public string 备注 { get; set; }
    }
}
