//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class platform
    {
        public long id { get; set; }
        public string user { get; set; }
        public string password { get; set; }
        public string platform1 { get; set; }
    }
}
